### ISSUE TITLE
fixed some errors....

### ISSUE THREAD

**Issue by MichaelTen** [gavi/chatgpt-markdown#2]
if anyone is having some errors with the python script provided here... 

the following may prevent/bypass those errors.

https://github.com/Tenqido/chatgpt-markdown/blob/main/convertcleanall.py

Limitless peace! Bless up!

**Comment by gavi** [comment]
Hey @MichaelTen  - I am open to incorporate your changes. Please give me a pull request.

**Comment by MichaelTen** [comment]
hi. thanks. i think i did this correctly, but if i didn't please let me know. 

https://github.com/Tenqido/chatgpt-markdown/pull/1

actually.. [edit... i may need to redo this.. properly]

bless up.

**Comment by MichaelTen** [comment]
ok. i think i did it correctly now. please let me know if  i should try again. 

https://github.com/gavi/chatgpt-markdown/pull/3/commits/93c8ae625964546d4a310de7ca37e8416824e5ee

thanks and limitless peace.

**Comment by gavi** [comment]
merged

**Comment by MichaelTen** [comment]
thanks. this morning, i also actually added a couple more features since i sent that pull request you just merged. please let me know if I can/should send a pull request for this also. 

https://github.com/Tenqido/chatgpt-markdown/blob/main/convertversmore.py

added feature/fixes are, "also added feature to not over ride duplicate chats with same name (add _v1, _v2, and so forth). 
and also not not generate .md files with no name, which can happen for some reason, like ".md" (which obsidian will not show. instead it names those "noname" and "noname_v1" and so on. "

cheers and limitless peace.

**Comment by gavi** [comment]
Yes, Please provide a PR @MichaelTen

**Comment by MichaelTen** [comment]
done. https://github.com/gavi/chatgpt-markdown/pull/4

thanks.

**Comment by MichaelTen** [comment]
i fixed some more new errors in formatting. a ## system started being added at the top of exported parsed markdowns in the last few weeks. and a duplicate ## assistant frequently. please test this as helpful. but i think if fixed those with this patch. .

https://github.com/gavi/chatgpt-markdown/pull/5

cheers and bless up.
